name: k8s image transfer to gcr
on: [push]
jobs:
  transfer:
    name: transfer-gcr-image
    runs-on: ubuntu-latest
    steps:
    - name: docker-login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: checkout
      uses: actions/checkout@master
    - name: execute script 
      run: |
        ./transfer.sh
