name: k8s image transfer to ghcr
on: [push]
jobs:
  transfer:
    name: transfer-ghcr-image
    runs-on: ubuntu-latest
    steps:
    - name: docker-login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: checkout
      uses: actions/checkout@master
    - name: execute script 
      run: |
        ./transfer-to-registry.sh
        docker images
