name: k8s image transfer
on: [push]
jobs:
  transfer:
    name: transfer-pkg-image
    runs-on: ubuntu-latest
    steps:
    - name: docker-login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: checkout
      uses: actions/checkout@master
    - name: execute script 
      run: |
        ./transfer-to-registry.sh
