name: registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Build and publish Docker Image to GitHub Packages Registry
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          registry: ghcr.io
          username: ${{ github.REGISTRY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          github-token: ${{ secrets.REGISTRY_TOKEN }}
          image-name: gcr-image-transfer
          extract-git-tag: true 
